import nextConfig from "eslint-config-next";

const eslintConfig = [
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/out/**",
      "**/build/**",
      "**/dist/**",
      "**/.cache/**",
      "**/coverage/**",
      "**/.turbo/**",
      "**/public/**",
      "**/src/shared/graphql/**", // Auto-generated by GraphQL Codegen
    ],
  },
  ...nextConfig,
  {
    files: ["**/*.{js,mjs,cjs,jsx,ts,tsx}"],
    rules: {
      // Disable overly strict React rules for valid patterns
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/purity": "off",
    },
  },
];

export default eslintConfig;
